In [3]:
import geopandas as gpd

In [33]:
df = gpd.read_file('./public/madison_parcels.json')

In [34]:
df['PropertyUse'].value_counts()

PropertyUse
Single family          49577
Condominium            16952
2 Unit                  3232
Vacant                  2651
Apartments              2187
                       ...
Florist -greenhouse        1
Rs vacant                  1
Shop, 1 story lg.          1
Station -use change        1
R-2 parking lot            1
Name: count, Length: 145, dtype: int64

In [35]:
list(df.columns)

['OwnerName1', 'OwnerName2', 'Address', 'PropertyUse', 'Zoning1', 'geometry']

In [12]:
df.head()

,OBJECTID,Parcel,XRefParcel,Address,DateParcelChanged,PropertyClass,PropertyUse,AssessmentArea,AreaName,MoreThanOneBuild,...,StormOutfall,FireDemandZone,FireDemandSubZone,PropertyChangeDate,MaxConstructionYear,XCoord,YCoord,SHAPE_Length,SHAPE_Area,geometry
0,1,070929404013,070929404013,4329 Tokay Blvd,2025-06-17 09:57:00+00:00,Exempt,Vacant,6601.0,Residential Exempt,YES,...,None,None,None,NaT,0,803477.952926,474963.648285,0.003347,6.689583e-07,"MULTIPOLYGON (((-89.44983 43.0531, -89.44984 4..."
1,2,070929405079,070929405079,4514 Wakefield St,2025-06-17 09:57:00+00:00,Residential,Single family,74.0,Midvale Heights - Odana,NO,...,None,None,None,NaT,0,802661.200439,474919.702511,0.001316,1.029882e-07,"MULTIPOLYGON (((-89.45325 43.05313, -89.45325 ..."
2,3,070929405095,070929405095,4506 Wakefield St,2026-01-31 21:41:00+00:00,Residential,Single family,74.0,Midvale Heights - Odana,NO,...,None,None,None,NaT,0,802816.502678,474915.689528,0.001174,8.576612e-08,"MULTIPOLYGON (((-89.45298 43.05282, -89.45297 ..."
3,4,070929405243,070929405243,4605 Tokay Blvd,2026-01-31 21:41:00+00:00,Residential,Single family,74.0,Midvale Heights - Odana,NO,...,None,None,None,NaT,0,802476.500440,475032.602589,0.001274,1.012761e-07,"MULTIPOLYGON (((-89.45426 43.05313, -89.45426 ..."
4,5,070929406027,070929406027,662 Odell St,2026-01-31 21:41:00+00:00,Residential,Single family,74.0,Midvale Heights - Odana,NO,...,None,None,None,NaT,0,802539.511605,473836.524797,0.001211,9.012038e-08,"MULTIPOLYGON (((-89.45399 43.0502, -89.45375 4..."

In [6]:
important_columns = ["Address", "PropertyUse", "geometry"]

In [20]:
df[df['Address'] == '411 E Johnson St'].to_clipboard()

In [37]:
df.head()

,OwnerName1,OwnerName2,Address,PropertyUse,Zoning1,geometry
0,MIDVALE COMMUNITY,LUTHERAN CHURCH,4329 Tokay Blvd,Vacant,None,"POLYGON ((-89.44983 43.0531, -89.44984 43.0527..."
1,"FRIEDLAND, LEWIS A",& STACEY J OLIKER,4514 Wakefield St,Single family,None,"POLYGON ((-89.45325 43.05313, -89.45325 43.052..."
2,"SCHLOUGH, BRADLEY & MARY",,4506 Wakefield St,Single family,None,"POLYGON ((-89.45298 43.05282, -89.45297 43.053..."
3,"POWLES, BRENDA LYNN",DEREK J POWLES,4605 Tokay Blvd,Single family,None,"POLYGON ((-89.45426 43.05313, -89.45426 43.053..."
4,"CAPICIK, CARL W",& NANCY K WHITNEY,662 Odell St,Single family,None,"POLYGON ((-89.45399 43.0502, -89.45375 43.0502..."

In [23]:
df['PropertyUse'].value_counts().to_clipboard()

In [24]:
residental_uses = ['Single family', '2 Unit', '3 Unit', 'Apartments', 'Apartment & office', 'Apartment & store', 'Apartments & rooms', 'Apartment Sec 42', 'Rooming house', 'Condominium', 'Condominium-Notation','Condominium-Warehouse', 'Condominium -apt', 'Condominium -other']

In [38]:
residental_df = df[df['PropertyUse'].isin(residental_uses)]

In [ ]:
residental_df.to_file('residential.geojson', driver='GeoJSON')

In [46]:
def check_for_llc(owner):
    if owner.find('LLC') != -1:
        return True
    return False

In [45]:
"STEVE BROWN LLC".find('LLC')

12

In [59]:
single_family_df = residental_df[residental_df['PropertyUse'] == 'Single family']
check_if_rented = (single_family_df['OwnerName1'].apply(check_for_llc)) | (single_family_df['OwnerName2'].apply(check_for_llc))
single_family_rented = single_family_df[check_if_rented]

In [60]:
single_family_rented

,OwnerName1,OwnerName2,Address,PropertyUse,Zoning1,geometry
15,646 S MIDVALE BLVD LLC,,646 S Midvale Blvd,Single family,None,"POLYGON ((-89.45134 43.05069, -89.45162 43.050..."
82,"5017 TOKAY, LLC",,5017 Tokay Blvd,Single family,None,"POLYGON ((-89.46472 43.05316, -89.46498 43.053..."
181,"ADVEMP HOLDINGS, LLC",,5826 Crabapple Ln,Single family,None,"POLYGON ((-89.48251 43.03528, -89.48251 43.034..."
501,MCJ GLOBAL LLC,,2614 Stevens St,Single family,None,"POLYGON ((-89.43232 43.07237, -89.43248 43.072..."
508,PARAMETRIC PROPERTY GROUP,LLC,2426 Kendall Ave,Single family,None,"POLYGON ((-89.42831 43.07176, -89.42831 43.071..."
...,...,...,...,...,...,...
81872,BROWN BUILDING LLC,,513 Pine St,Single family,None,"POLYGON ((-89.39213 43.05035, -89.39232 43.050..."
81944,JOHNSON & BROCK LLC,,641 Pickford St,Single family,None,"POLYGON ((-89.43104 43.0572, -89.43094 43.0571..."
82020,608 CHAPMAN LLC,,608 Chapman St,Single family,None,"POLYGON ((-89.4341 43.0565, -89.434 43.05641, ..."
82122,576 GATELY TERRACE LLC,,576 Gately Ter,Single family,None,"POLYGON ((-89.44689 43.05383, -89.44646 43.053..."
82199,526 ORCHARD DRIVE LLC,,526 Orchard Dr,Single family,None,"POLYGON ((-89.45673 43.05464, -89.45673 43.054..."

In [58]:
single_family_rented

1        False
2        False
3        False
4        False
5        False
         ...
82250    False
82251    False
82252    False
82253    False
82254    False
Length: 49577, dtype: bool